---
virtual_machines:
  hosts:
    debian:
      ansible_host: 192.168.23.100
      ansible_become: true
      ansible_become_method: sudo
      ansible_python_interpreter: /usr/bin/python3.13

#    ubuntu:
#      ansible_host: 192.168.23.101
#      ansible_become: true
#      ansible_become_method: sudo
#      ansible_python_interpreter: /usr/bin/python3.13

#    debian:
#      ansible_host: 172.16.237.100
#      ansible_become: true
#      ansible_become_method: sudo
#      ansible_python_interpreter: /usr/bin/python3.13

#    ubuntu:
#      ansible_host: 172.16.237.101
#      ansible_become: true
#      ansible_become_method: sudo
#      ansible_python_interpreter: /usr/bin/python3.13