#cd ~/Documents/Tech/Ansible-Playbook/docker

#ansible-vault encrypt /Users/troy/Documents/Tech/Ansible-Playbook/docker/docker_install/vars/main.yaml
#ansible-vault decrypt /Users/troy/Documents/Tech/Ansible-Playbook/docker/docker_install/vars/main.yaml

#ansible-playbook --ask-vault-password playbook.yaml -i inventory.yaml --ask-become-pass --key-file ~/.ssh/id_ecdsa
#ansible-playbook --ask-vault-password playbook.yaml -i inventory.yaml

---
- name: Install Docker Homelab
  hosts: virtual_machines
  become: true
  roles:
    - docker_install
    - ufw_install
    #- firewalld_install
    - dozzle_deploy
    - filebrowser_deploy
    #- alertmanager_deploy
    #- prometheus_deploy
    - telegraf_deploy
    - influxdb_deploy
    #- alloy_deploy
    #- loki_deploy
    #- grafana_deploy
    #- audiobookshelf_deploy
    #- bazarr_deploy
    #- ghost_deploy
    #- gitea_deploy
    #- gotify_deploy
    #- homepage_deploy
    #- jellyfin_deploy
    #- jellyseerr_deploy
    #- kavita_deploy
    #- memos_deploy
    #- mkvtoolnix_deploy
    #- myspeed_deploy
    #- overseerr_deploy
    #- plex_deploy
    #- prowlarr_deploy
    #- pulse_deploy
    #- radarr_deploy
    #- sonarr_deploy
    #- syncthing_deploy
    #- tautulli_deploy
    #- technitium_deploy
    #- transmission_deploy
    #- uptime-kuma_deploy
    #- vaultwarden_deploy
    #- whatsupdocker_deploy
    #- redis_deploy
    #- paperless-ngx_deploy
    #- mariadb_deploy
    #- photoprism_deploy
    #- postgresql_deploy
    #- umami_deploy
