#cd $HOME/Documents/Tech/Ansible-Playbook/server
#
#ansible-vault encrypt /Users/troy/Documents/Tech/Ansible-Playbook/server/server_install/vars/main.yaml
#ansible-vault decrypt /Users/troy/Documents/Tech/Ansible-Playbook/server/server_install/vars/main.yaml
#
#ansible-playbook --ask-vault-password playbook.yaml -i inventory.yaml --ask-become-pass --key-file $HOME/.ssh/id_ecdsa
#ansible-playbook --ask-vault-password playbook.yaml -i inventory.yaml

---
- name: Server Setup
  hosts: virtual_machines
  become: true
  roles:
    - server_install