global:
  scrape_interval: 15s
  evaluation_interval: 15s
  body_size_limit: 15MB
  sample_limit: 10000
  target_limit: 50
  label_limit: 100
  label_name_length_limit: 200
  label_value_length_limit: 200

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
